//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TSS.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSProcesoAutoDeterminacionSoap", Namespace="http://tempuri.org/")]
    public partial class WSProcesoAutoDeterminacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEncabezadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDetallesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetEncabezadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSProcesoAutoDeterminacion() {
            this.Url = global::TSS.Properties.Settings.Default.TSS_localhost_WSProcesoAutoDeterminacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetEncabezadosCompletedEventHandler GetEncabezadosCompleted;
        
        /// <remarks/>
        public event GetDetallesCompletedEventHandler GetDetallesCompleted;
        
        /// <remarks/>
        public event SetEncabezadoCompletedEventHandler SetEncabezadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string Input) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string Input) {
            this.HelloWorldAsync(Input, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string Input, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        Input}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEncabezados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Encabezado[] GetEncabezados() {
            object[] results = this.Invoke("GetEncabezados", new object[0]);
            return ((Encabezado[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEncabezadosAsync() {
            this.GetEncabezadosAsync(null);
        }
        
        /// <remarks/>
        public void GetEncabezadosAsync(object userState) {
            if ((this.GetEncabezadosOperationCompleted == null)) {
                this.GetEncabezadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEncabezadosOperationCompleted);
            }
            this.InvokeAsync("GetEncabezados", new object[0], this.GetEncabezadosOperationCompleted, userState);
        }
        
        private void OnGetEncabezadosOperationCompleted(object arg) {
            if ((this.GetEncabezadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEncabezadosCompleted(this, new GetEncabezadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDetalles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Detalle[] GetDetalles() {
            object[] results = this.Invoke("GetDetalles", new object[0]);
            return ((Detalle[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDetallesAsync() {
            this.GetDetallesAsync(null);
        }
        
        /// <remarks/>
        public void GetDetallesAsync(object userState) {
            if ((this.GetDetallesOperationCompleted == null)) {
                this.GetDetallesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetallesOperationCompleted);
            }
            this.InvokeAsync("GetDetalles", new object[0], this.GetDetallesOperationCompleted, userState);
        }
        
        private void OnGetDetallesOperationCompleted(object arg) {
            if ((this.GetDetallesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetallesCompleted(this, new GetDetallesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetEncabezado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetEncabezado(string TipoAutodeterminacion, string RNC, System.DateTime Periodo, string TipoDocumento, string Documento, string CodigoNomina, string Empleado) {
            object[] results = this.Invoke("SetEncabezado", new object[] {
                        TipoAutodeterminacion,
                        RNC,
                        Periodo,
                        TipoDocumento,
                        Documento,
                        CodigoNomina,
                        Empleado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetEncabezadoAsync(string TipoAutodeterminacion, string RNC, System.DateTime Periodo, string TipoDocumento, string Documento, string CodigoNomina, string Empleado) {
            this.SetEncabezadoAsync(TipoAutodeterminacion, RNC, Periodo, TipoDocumento, Documento, CodigoNomina, Empleado, null);
        }
        
        /// <remarks/>
        public void SetEncabezadoAsync(string TipoAutodeterminacion, string RNC, System.DateTime Periodo, string TipoDocumento, string Documento, string CodigoNomina, string Empleado, object userState) {
            if ((this.SetEncabezadoOperationCompleted == null)) {
                this.SetEncabezadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetEncabezadoOperationCompleted);
            }
            this.InvokeAsync("SetEncabezado", new object[] {
                        TipoAutodeterminacion,
                        RNC,
                        Periodo,
                        TipoDocumento,
                        Documento,
                        CodigoNomina,
                        Empleado}, this.SetEncabezadoOperationCompleted, userState);
        }
        
        private void OnSetEncabezadoOperationCompleted(object arg) {
            if ((this.SetEncabezadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetEncabezadoCompleted(this, new SetEncabezadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Encabezado {
        
        private int encabazadoIDField;
        
        private string tipoAutodeterminacionField;
        
        private string rNCField;
        
        private System.DateTime periodoField;
        
        private Detalle[] detallesField;
        
        /// <remarks/>
        public int EncabazadoID {
            get {
                return this.encabazadoIDField;
            }
            set {
                this.encabazadoIDField = value;
            }
        }
        
        /// <remarks/>
        public string TipoAutodeterminacion {
            get {
                return this.tipoAutodeterminacionField;
            }
            set {
                this.tipoAutodeterminacionField = value;
            }
        }
        
        /// <remarks/>
        public string RNC {
            get {
                return this.rNCField;
            }
            set {
                this.rNCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public Detalle[] Detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Detalle {
        
        private int detalleIDField;
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        private string codigoNominaField;
        
        private string empleadoField;
        
        /// <remarks/>
        public int DetalleID {
            get {
                return this.detalleIDField;
            }
            set {
                this.detalleIDField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNomina {
            get {
                return this.codigoNominaField;
            }
            set {
                this.codigoNominaField = value;
            }
        }
        
        /// <remarks/>
        public string Empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetEncabezadosCompletedEventHandler(object sender, GetEncabezadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEncabezadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEncabezadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Encabezado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Encabezado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDetallesCompletedEventHandler(object sender, GetDetallesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDetallesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDetallesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Detalle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Detalle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SetEncabezadoCompletedEventHandler(object sender, SetEncabezadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetEncabezadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetEncabezadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591